"""empty message

Revision ID: b2440d662cbe
Revises: 4c80de54a9e0
Create Date: 2020-12-07 15:49:49.458926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2440d662cbe'
down_revision = '4c80de54a9e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stuff', sa.Column('email', sa.String(length=128), nullable=True))
    op.alter_column('user_stuff', 'username',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_user_stuff_email'), 'user_stuff', ['email'], unique=True)
    op.create_index(op.f('ix_user_stuff_username'), 'user_stuff', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_stuff_username'), table_name='user_stuff')
    op.drop_index(op.f('ix_user_stuff_email'), table_name='user_stuff')
    op.alter_column('user_stuff', 'username',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('user_stuff', 'email')
    # ### end Alembic commands ###
